Repository AnubisLMS/Anubis, pull requests merged in 2021-08, with the labels that each got.

#196 CLN summer cleaning 4
  api/anubis/utils/k8s/pipeline.py
  api/anubis/views/public/auth.py
  docs/anubis-design.pdf
  docs/design-tex/overview.tex
  docs/development_guide.md
  docs/posts/1.md
  docs/posts/2.md
  k8s/chart/templates/network-policy.yml
  k8s/chart/templates/pipeline-api.yml
  k8s/chart/templates/web.yml
  k8s/chart/values.yaml
  k8s/restart.sh
  theia/ide/admin/Dockerfile
  theia/ide/admin/cli/anubis/cli.py
  theia/ide/xv6/Dockerfile
  theia/proxy/index.js
Labels: backend, housekeeping

#198 CLN summer cleaning 5
  api/anubis/views/admin/auth.py
  k8s/chart/templates/api.yml
  k8s/chart/templates/pipeline-api.yml
  k8s/chart/templates/theia.yml
  k8s/chart/templates/web.yml
  web/Dockerfile
  web/src/Pages/Admin/Users.jsx
Labels: housekeeping, frontend, backend

#207 RM github classrooms
  api/anubis/models/__init__.py
  api/anubis/rpc/seed.py
  api/anubis/utils/github/__init__.py
  api/anubis/utils/github/api.py
  api/anubis/utils/github/fix.py
  api/anubis/utils/github/parse.py
  api/anubis/utils/github/repos.py
  api/anubis/utils/k8s/theia.py
  api/anubis/utils/lms/assignments.py
  api/anubis/utils/seed.py
  api/anubis/views/admin/assignments.py
  api/anubis/views/public/repos.py
  api/jobs/reaper.py
  api/migrations/versions/145674891fee_add_assignment_repo_timestamps.py
  api/migrations/versions/2d4e34d460e8_rm_github_classrooms.py
  api/tests/test_assignment_admin.py
  docker-compose.yml
  theia/ide/admin/cli/anubis/assignment/meta.yml
  web/src/Components/Public/Assignments/AssignmentCard.jsx
  web/src/Pages/Admin/Assignment/Assignment.jsx
Labels: feature, backend

#211 FIX issues with github classroom removal
  api/anubis/views/admin/courses.py
  api/anubis/views/public/webhook.py
  api/jobs/reaper.py
  api/migrations/versions/2d4e34d460e8_rm_github_classrooms.py
Labels: bug

#214 CHG managed db
  api/Dockerfile
  api/anubis/rpc/theia.py
  api/docker-entrypoint.sh
  api/jobs/backup.sh
  api/requirements.in
  api/requirements.txt
  api/rq-worker.sh
  k8s/chart/templates/api.yml
  k8s/chart/templates/backup-cron.yml
  k8s/chart/templates/migrate.yml
  k8s/chart/templates/pipeline-api.yml
  k8s/chart/templates/reaper-cron.yml
  k8s/chart/templates/rpc.yml
  k8s/chart/templates/theia.yml
  k8s/chart/templates/visuals-cron.yml
  k8s/chart/values.yaml
  theia/proxy/index.js
  theia/proxy/package.json
  theia/proxy/yarn.lock
Labels: housekeeping, backend

#216 FIX some minor issues with course management page
  web/src/Pages/Admin/Course.jsx
Labels: bug, frontend

#218 FIX professor permission & tune k8s hpas
  api/anubis/models/__init__.py
  api/anubis/utils/lms/courses.py
  api/anubis/views/admin/assignments.py
  api/migrations/versions/592c0d556edf_rm_unused_course_column.py
  k8s/chart/templates/api.yml
  k8s/chart/templates/hpa.yml
  k8s/chart/templates/rpc.yml
  k8s/chart/templates/theia.yml
  k8s/chart/templates/web.yml
  web/src/Pages/Admin/Assignment/Assignment.jsx
  web/src/Pages/Admin/Course.jsx
Labels: bug, frontend, backend

#219 FIX professor permission in anubis.utils.lms.courses.is_course_superuser
  api/anubis/utils/lms/courses.py
Labels: bug, backend

#223 CHG tune hpas for student load
  api/anubis/views/public/ide.py
  k8s/chart/templates/hpa.yml
  k8s/chart/values.yaml
Labels: housekeeping, backend

#213 CHG Theia Poller Job
  api/anubis/rpc/theia.py
  api/jobs/poller.py
  k8s/chart/templates/rpc.yml
  k8s/chart/templates/theia.yml
  k8s/chart/values.yaml
  k8s/debug/provision.sh
  k8s/debug/upgrade.sh
  k8s/restart.sh
  web/src/Components/Public/IDE/IDEDialog.jsx
Labels: backend
