Repository AnubisLMS/Anubis, pull requests merged in 2021-07, with the labels that each got.

#147 ADD dialog with description
  web/src/Components/Public/Assignments/AssignmentCard.jsx
  web/src/Pages/Public/Assignments.jsx
Labels: feature, frontend

#162 Fix whoami bug
  api/anubis/models/__init__.py
  api/anubis/utils/lms/courses.py
Labels: backend, bug

#167 Fix issues with tests
  .github/workflows/test-api.yml
  .github/workflows/test-web.yml
  api/anubis/app.py
  api/anubis/config.py
  api/anubis/utils/lms/courses.py
  api/anubis/utils/services/cache.py
  api/anubis/utils/services/rpc.py
  api/anubis/views/public/webhook.py
  api/dev.py
  api/tests/mintest.sh
  api/tests/test.sh
  api/tests/test_visuals_admin.py
  api/tests/test_webhook_public.py
  api/tests/utils.py
  web/src/setupProxy.js
Labels: backend, bug, housekeeping

#169 Add GitHub button
  Makefile
  docs/development_guide.md
  web/Makefile
  web/src/App.jsx
  web/src/Components/Navigation/Nav.jsx
Labels: feature, frontend, housekeeping

#172 FIX github commit query hardcode
  api/anubis/models/__init__.py
  api/anubis/utils/services/github.py
  api/jobs/reaper.py
Labels: backend, bug

#174 Fix readme images urls
  README.md
  docs/old-anubis-design.md
Labels: bug, documentation

#175 FIX image paths in readme
  README.md
Labels: bug, documentation

#176 ADD image puller
  Makefile
  docker-compose.yml
  docs/img
  k8s/chart/templates/hpa.yml
  k8s/chart/templates/puller.yml
  k8s/chart/values.yaml
  k8s/debug/provision.sh
  k8s/debug/restart.sh
  k8s/deploy.sh
  puller/.dockerignore
  puller/.gitignore
  puller/Dockerfile
  puller/README.md
  puller/go.mod
  puller/go.sum
  puller/main.go
Labels: backend, bug

#177 CHG mariadb galera
  k8s/prod/Makefile
  k8s/prod/mariadb-values.yaml
Labels: backend, feature

#179 CHG lock down container security
  api/Dockerfile
  api/anubis/utils/k8s/pipeline.py
  api/anubis/utils/k8s/theia.py
  api/docker-entrypoint.sh
  k8s/chart/templates/api.yml
  k8s/chart/templates/backup-cron.yml
  k8s/chart/templates/hpa.yml
  k8s/chart/templates/ingress.yml
  k8s/chart/templates/pipeline-api.yml
  k8s/chart/templates/puller.yml
  k8s/chart/templates/rpc.yml
  k8s/chart/templates/theia.yml
  k8s/chart/templates/web.yml
  k8s/chart/values.yaml
  k8s/debug/provision.sh
  k8s/debug/restart.sh
  k8s/prod/mairadb-values.yaml
  theia/ide/admin/Dockerfile
  theia/ide/admin/cli/anubis/assignment/Dockerfile
  theia/ide/admin/cli/anubis/assignment/pipeline.py
  theia/ide/admin/cli/anubis/assignment/utils.py
  theia/proxy/Dockerfile
  theia/sidecar/Dockerfile
  theia/sidecar/supervisord.conf
  web/package.json
  web/yarn.lock
Labels: backend, security

#180 CHG same domain theia
  api/anubis/config.py
  api/anubis/utils/lms/theia.py
  docker-compose.yml
  k8s/chart/templates/api.yml
  k8s/chart/templates/ingress.yml
  k8s/chart/templates/rpc.yml
  k8s/chart/values.yaml
  k8s/debug/provision.sh
  k8s/prod/Makefile
  theia/ide/xv6/Dockerfile
  theia/proxy/index.js
Labels: backend, feature, housekeeping

#183 FIX some issues that came up while resetting prod
  k8s/prod/Makefile
  k8s/prod/filebeat-values.yaml
  k8s/prod/mariadb-values.yaml
Labels: bug

#187 v3.1.27 CLN summer cleaning
  api/alembic.ini
  api/anubis/app.py
  api/anubis/config.py
  api/anubis/models/__init__.py
  api/anubis/utils/auth.py
  api/anubis/utils/http/decorators.py
  api/anubis/utils/http/files.py
  api/anubis/utils/http/https.py
  api/anubis/utils/lms/assignments.py
  api/anubis/utils/lms/courses.py
  api/anubis/utils/lms/lectures.py
  api/anubis/utils/lms/theia.py
  api/anubis/utils/services/github.py
  api/anubis/utils/services/migrate.py
  api/anubis/views/admin/assignments.py
  api/anubis/views/admin/courses.py
  api/anubis/views/admin/ide.py
  api/anubis/views/admin/lectures.py
  api/anubis/views/admin/static.py
  api/anubis/views/admin/students.py
  api/anubis/views/public/assignments.py
  api/anubis/views/public/auth.py
  api/anubis/views/public/courses.py
  api/anubis/views/public/ide.py
  api/anubis/views/public/lectures.py
  api/anubis/views/public/profile.py
  api/anubis/views/public/questions.py
  api/anubis/views/public/repos.py
  api/anubis/views/public/submissions.py
  api/anubis/views/public/webhook.py
  api/dev.py
  api/jobs/reaper.py
  api/jobs/visuals.py
  api/migrations/versions/2324a3537ff3_fix_index_issues.py
  api/migrations/versions/2af8f3918f87_add_github_org_url.py
  api/migrations/versions/31dc6a1a6759_add_autograde_tests_repo.py
  api/migrations/versions/3890c28bd2cb_add_custom_join_code.py
  api/migrations/versions/3ed4da84667e_add_accept_late_to_assignments.py
  api/migrations/versions/65be3bf01dae_chg_replace_lecture_notes_number_with_.py
  api/migrations/versions/716e3e14891d_add_late_exceptions.py
  api/migrations/versions/a622f56b9050_add_accepted_column.py
  api/migrations/versions/bf3ae1de1d12_chg_rename_sequence_to_pool.py
  api/migrations/versions/c9f4c87534a5_add_lecture_notes.py
  api/tests/test_lectures_admin.py
  api/tests/test_lectures_public.py
  api/tests/test_visuals_admin.py
  api/tests/test_webhook_public.py
  api/tests/utils.py
  k8s/chart/templates/backup-cron.yml
  theia/ide/admin/autosave
  theia/ide/admin/motd.txt
  theia/ide/xv6/autosave
  theia/sidecar/autosave-loop.sh
Labels: housekeeping

#188 ADD export assignment questions functions and views
  api/anubis/utils/lms/questions.py
  api/anubis/views/admin/questions.py
  api/docker-entrypoint.sh
  web/Dockerfile
  web/public/index.html
  web/src/Components/Admin/Assignment/QuestionControls.jsx
  web/src/Pages/Admin/Autograde/Results.jsx
Labels: backend, feature

#191 CLN summer cleaning 2
  README.md
  api/anubis/utils/auth.py
  api/anubis/utils/seed.py
  docker-compose.yml
  docs/README.md
  docs/anubis-design.pdf
  docs/design-tex/Makefile
  docs/design-tex/anubis-design.tex
  docs/design-tex/autograding.tex
  docs/design-tex/cloud_ides.tex
  docs/design-tex/deployment.tex
  docs/design-tex/insights.tex
  docs/design-tex/overview.tex
  docs/design-tex/services.tex
  k8s/chart/templates/web.yml
  web/Dockerfile
  web/src/Components/Admin/Users/UserCard.jsx
  web/src/Pages/Admin/Autograde/Results.jsx
Labels: housekeeping
