Repository AnubisLMS/Anubis, pull requests merged in 2021-06, with the labels that each got.

#120 Fix typos in README.md
  README.md
  docs/anubis.pdf
Labels: housekeeping

#129 FIX undefined on some user searches in admin panel
  api/anubis/views/admin/students.py
Labels: bug

#130 FIX add professor button is not checking for course sepecific record
  api/anubis/views/admin/courses.py
Labels: bug

#132 ADD an a motd to the anubis cloud ide terminals
  k8s/debug/restart.sh
  theia/ide/xv6/Dockerfile
  theia/ide/xv6/motd.txt
Labels: feature

#128 Remove redundant DATABASE_URI assignment
  api/anubis/config.py
Labels: housekeeping

#137 Add simple bare metal debugging
  Makefile
  README.md
  api/Makefile
  api/anubis/app.py
  api/anubis/config.py
  api/anubis/models/__init__.py
  api/anubis/utils/http/files.py
  api/anubis/utils/services/migrate.py
  api/anubis/utils/services/rpc.py
  api/dev.py
  api/migrations/env.py
  api/migrations/versions/0be9593348ba_init.py
  api/migrations/versions/265635dac5b6_add_theia_options.py
  api/requirements.in
  api/requirements.txt
  docker-compose.yml
  docs/anubis.pdf
  theia/proxy/package.json
  web/package.json
  web/src/Pages/Admin/Lectures.jsx
  web/src/setupProxy.js
  web/yarn.lock
Labels: feature, housekeeping

#146 CHG add polling to assignments so ide button works when repo link active
  web/.eslintrc.yml
  web/src/Components/Public/Assignments/AssignmentCard.jsx
  web/src/Pages/Admin/Assignment/Assignment.jsx
  web/src/Pages/Public/Assignments.jsx
Labels: feature

#145 ADD contribution guidelines
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/greetings.yml
  .github/workflows/stale.yml
  .gitignore
  Makefile
  README.md
  api/requirements.txt
  docs/README.md
  docs/anubis.pdf
  docs/development_guide.md
  docs/render.sh
  k8s/debug/provision.sh
  theia/proxy/yarn-error.log
Labels: housekeeping

#148 FIX logo image url in readme
  README.md
Labels: bug, housekeeping

#149 FIX potential issue with polling
  web/src/Components/Public/Assignments/AssignmentCard.jsx
  web/src/Pages/Public/Assignments.jsx
Labels: bug, frontend

#151 CHG replace lectures notes number posting time
  api/anubis/models/__init__.py
  api/anubis/utils/lms/lectures.py
  api/anubis/views/admin/lectures.py
  api/migrations/versions/65be3bf01dae_chg_replace_lecture_notes_number_with_.py
  docker-compose.yml
  docs/development_guide.md
  k8s/prod/mairadb-values.yaml
  web/src/Components/Admin/Lecture/LectureEditDialog.jsx
  web/src/Components/Admin/Lecture/LectureUploadDialog.jsx
  web/src/Pages/Admin/Lectures.jsx
  web/src/Pages/Public/Lectures.jsx
  web/src/navconfig.jsx
Labels: backend, feature, frontend
